### ISSUE TITLE
CSS flex 布局

### ISSUE THREAD

**Issue by lTBeL** [lTBeL/lTBeL.github.io#13]
指定flex 布局
```css
.box{
  display: flex;
  display: -webkit-flex; //webkit内核
}
```
>flex container 和 flex item      main axis      cross axis

**Comment by lTBeL** [comment]
>item 属性
```css
order
flex-grow
flex-shrink
flex-basis
flex
align-self
```
>order：item的排列顺序。数值越小，排列越靠前，默认为0。
```css
.item {
  order: <integer>;
}
```
>flex-grow：item放大的权重，默认为0，即如果存在剩余空间，也不放大。
```css
.item {
  flex-grow: <number>; /* default 0 */
}
```
>flex-shrink：定义了item的缩小比例，默认为1，即如果空间不足，该item将缩小。0 不缩小？
```css
.item {
  flex-shrink: <number>; /* default 1 */
}
```
>flex-basis ：在分配多余空间之前，item占据的主轴空间（main size）。浏览器根据这个属性，计算主轴是否有多余空间。它的默认值为auto，即item的本来大小。
```css
.item {
  flex-basis: <length> | auto; /* default auto */
}
```
>flex属性是flex-grow, flex-shrink 和 flex-basis的简写，默认值为0 1 auto。后两个属性可选。
```css
.item {
  flex: none | [ <'flex-grow'> <'flex-shrink'>? || <'flex-basis'> ]
}
```
>align-self属性允许单个item有与其他item不一样的对齐方式，可覆盖align-items属性。默认值为auto，表示继承父元素的align-items属性，如果没有父元素，则等同于stretch。
```css
.item {
  align-self: auto | flex-start | flex-end | center | baseline | stretch;
}
```
